#%RAML 1.0 NamedExample
value:
  -
    ID: 1 
    date: 19/10/2022
    dueDate: 19/11/2022
    unitConsumed: 20
    billAmount: 120 
  -
    ID: 2 
    date: 11/10/2022
    dueDate: 11/11/2022
    unitConsumed: 50
    billAmount: 500
  -
    ID: 3
    date: 13/10/2022
    dueDate: 13/11/2022
    unitConsumed: 40
    billAmount: 240
 
     