#%RAML 1.0 NamedExample
value:
  -
    connectionId: 1
    consumerNumber: 1234
    applicationDate: 2021-01-02
    connectionDate: 2021-02-02
    connectionStatus: true
    customerConnection: { }
    connectionAddress:
      addressId: 1
      flatOrHouseNumber: 10
      buildingName: King's plaza
      landmark: Reave street
      village: Cuncolim
      taluka: South
      district: Salcete
      state: Goa
      pincode: "400344"
    connectionType: NON_INDUSTRIAL

  -
    connectionId: 2
    consumerNumber: 2345
    applicationDate: 2021-01-02
    connectionDate: 2021-02-02
    connectionStatus: false
    customerConnection: { }
    connectionAddress:
      addressId: 2
      flatOrHouseNumber: 11
      buildingName: Queen's plaza
      landmark: Naive street
      village: Assolna
      taluka: South
      district: Salcete
      state: Goa
      pincode: "400544"
    connectionType: INDUSTRIAL
  -

    connectionId: 3
    consumerNumber: 3456
    applicationDate: 2021-01-02
    connectionDate: 2021-02-02
    connectionStatus: true
    customerConnection: { }
    connectionAddress:
      addressId: 3
      flatOrHouseNumber: 12
      buildingName: Jack's plaza
      landmark: Jack street
      village: Quepem
      taluka: North
      district: Salcete
      state: Goa
      pincode: "420344"
    connectionType: NON_INDUSTRIAL        