#%RAML 1.0 NamedExample
value:
  -
    ReadingId: 101
    Units Consumed: 30
    Reading Photo: EEs1233455
    Reading Date: 2022/11/01
    PricePerUnits: 10
  -
    ReadingId: 102
    Units Consumed: 25
    Reading Photo: EEs1233475
    Reading Date: 2022/10/01
    PricePerUnits: 10