#%RAML 1.0 NamedExample

value:
  -

    paymentID: 1
    paymentDate: 2022-09-02
    totalPaymentCharges: 20
    totalPaid: 2000
    status: paid
    paymentMode: CREDIT

  -
    paymentID: 2
    paymentDate: 2022-09-03
    totalPaymentCharges: 20
    totalPaid: 4000
    status: paid
    paymentMode: DEBIT




    