#%RAML 1.0
title: Payment


  
/viewHistoricalPayment/{consumerNumber}:
  get:

    responses:
      200:
        body:
          application/json:
            example: !include /Example/PaymentExample.raml

/sendEmailOnPayment/{consumerNumber}:
  post:
    queryParameters:
      email:
        required: false
      
    responses:
      200:
        body:
          application/json:
            example:
              message: "Email sent successfully"


/payBill/{consumerNumber}:
  post:
    queryParameters:
      payMode:
        required: true
        enum:
          - CREDIT
          - DEBIT
          - WALLET
          - NETBANKING

    responses:
      200:
        body:
          application/json:
            example:
              message : "Bill paid!!"
      
  


    