#%RAML 1.0 NamedExample
value:
  connectionId: 1
  consumerNumber: 1234
  applicationDate: 2021-01-02
  connectionDate: 2021-02-02
  connectionStatus: true
  customerConnection: !include CustomerExample.raml
  connectionAddress:
    addressId: 1
    flatOrHouseNumber: 10
    buildingName: King's plaza
    landmark: Reave street
    village: Cuncolim
    taluka: South
    district: Salcete
    state: Goa
    pincode: "400344"
  connectionType: NON_INDUSTRIAL